#!/usr/bin/env python3
"""Bakes an HCE weights .txt into a C++ source file for `explain`.

The .txt is what `HceWeightsFile` reads: a few `#` header lines, then one
weight per line. The engine skips blank and `#` lines and applies
`(float)strtod` to the rest, so the embedded array has to hold the same
float32 bit patterns as that read, not merely values close to them.

That is why every value is written with `%.9g` of the float32. Nine
significant digits are always enough to recover a float32 exactly, while
`%.6f` is not: the smallest weight in `hce-v2/rank-contact.txt` is about
6.1e-23, and `%.6f` prints it as `0.000000`. Every literal is checked
against the float32 it came from before it is written, and a mismatch
aborts the run instead of embedding a wrong weight.
"""

from __future__ import annotations

import argparse
import hashlib
import math
import struct
from pathlib import Path

REPO_ROOT = Path(__file__).resolve().parent.parent
DEFAULT_OUT = REPO_ROOT / "source/eval/hce/hce_explain_weights_embedded.cpp"

#: How many weights share one output line. Purely cosmetic.
VALUES_PER_LINE = 8

#: The one layout this script knows how to describe. Anything else just
#: gets its bare count -- decoding an unfamiliar layout from a weight
#: count would be a guess, and a guess in a generated header is worse
#: than no description at all.
KNOWN_LAYOUTS = {
    4474: "material 17 + mobility 4407 + king_safety 50 (rank+contact, folded)",
}


def to_f32(value: float) -> float:
    """Round a Python float to the nearest float32, the same cast the
    engine applies to what `strtod` returns."""
    return struct.unpack("<f", struct.pack("<f", value))[0]


def parse_input(path: Path) -> tuple[list[str], list[float]]:
    """Parses a weights .txt the way the engine does: skip lines that are
    empty after stripping or start with `#`, and float32 the rest.

    Returns the `#` header lines (verbatim, no leading `#`/space) and the
    weight values as float32.
    """
    headers: list[str] = []
    values: list[float] = []
    for line in path.read_text().splitlines():
        stripped = line.strip()
        if not stripped:
            continue
        if stripped.startswith("#"):
            rest = stripped[1:]
            if rest.startswith(" "):
                rest = rest[1:]
            headers.append(rest)
            continue
        values.append(to_f32(float(stripped)))
    return headers, values


def format_literal(value: float) -> str:
    """`%.9g` of a float32, turned into a valid C++ `float` literal.

    `%.9g` can produce a bare integer like `3` or `-0`; `3f` is not a
    valid C++ float literal (only `3.f`/`3.0f` are), so a literal with
    neither `.` nor `e`/`E` gets a `.` inserted before the `f` suffix.
    The result is round-trip checked: parsing the literal's digits back
    through the same float32 cast must reproduce the exact same bits as
    `value`, or the run aborts rather than embed a mismatch.
    """
    if math.isnan(value) or math.isinf(value):
        raise SystemExit(f"refusing to embed a non-finite weight: {value!r}")
    text = "%.9g" % value
    if "." not in text and "e" not in text and "E" not in text:
        text += "."

    round_tripped = to_f32(float(text))
    if struct.pack("<f", round_tripped) != struct.pack("<f", value):
        raise SystemExit(
            f"literal {text!r} does not round-trip: wrote {value!r}, "
            f"read back {round_tripped!r}"
        )
    return text + "f"


def layout_line(n: int) -> str:
    layout = KNOWN_LAYOUTS.get(n)
    return f"{n} floats = {layout}" if layout else f"{n} floats"


def render(input_path: Path, headers: list[str], values: list[float]) -> str:
    digest = hashlib.sha256(input_path.read_bytes()).hexdigest()
    n = len(values)
    literals = [format_literal(v) for v in values]

    rows = [
        "\t" + ", ".join(literals[i : i + VALUES_PER_LINE]) + ","
        for i in range(0, n, VALUES_PER_LINE)
    ]
    body = "\n".join(rows)
    header_comment = "\n".join("//   " + h for h in headers)

    return f"""// AUTO-GENERATED by script/embed_hce_explain_weights.py. Do not edit by hand.
// Input  : {input_path.name}
// sha256 : {digest}
// Layout : {layout_line(n)}
//
{header_comment}

#include "../../config.h"

#if defined(USE_HCE_EXPLAIN)

namespace YaneuraOu {{
namespace Eval {{ namespace Hce {{

extern const int kEmbeddedHceWeightsSize = {n};

extern const float kEmbeddedHceWeights[{n}] = {{
{body}
}};

}} }} // namespace Eval::Hce
}} // namespace YaneuraOu

#endif // USE_HCE_EXPLAIN
"""


def main(argv: list[str] | None = None) -> int:
    ap = argparse.ArgumentParser(description=__doc__.splitlines()[0])
    ap.add_argument("input", type=Path, help="weights .txt, e.g. hce-v2/rank-contact.txt")
    ap.add_argument("-o", "--out", type=Path, default=DEFAULT_OUT, help="output .cpp path")
    args = ap.parse_args(argv)

    headers, values = parse_input(args.input)
    text = render(args.input, headers, values)
    args.out.parent.mkdir(parents=True, exist_ok=True)
    args.out.write_text(text)
    print(f"[embed] {args.out} <- {args.input} ({len(values)} weights)")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
